name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Echo package
        run: |
          echo "Packing package"
          cd NugetPubTest
          dotnet pack
          
          cd bin/Debug
          echo "$PWD"
          file="ruaruarua"
          yourfilenames=`ls ./*.nupkg`
          for eachfile in $yourfilenames
          do
            echo $eachfile
            file=$eachfile
          done
          
          echo "File is: $file"

          if [ -e "$file" ]; then
              echo "File exists"
          else 
              echo "File does not exist"
          fi
